### ISSUE TITLE
Bot doesn't input full e-mail adress

### ISSUE THREAD

**Issue by devlerr** [MattFlood7/LinkedInBot#5]
I set the bot up, but when it tries to login, it only uses first 5 letters of my e-mail adress and not the rest. (instead of john.smith@email.com it puts johns). Password input works fine.

What could cause this?

**Comment by devlerr** [comment]
Replacing 'lxml' with 'html.parser' partially solved the problem. The bot redirected to LinkedIn signedup page, but registred it as a successful login. I was able to login manually and the bot starts "working", printing "|".

**Comment by hossein890** [comment]
does it solved?

**Comment by aferreira44** [comment]
I used EMAIL instead of USERNAME as an env variable. USERNAME was getting my OS username, instead of the correct string of my .env file.

I think my PR #11 solves this error. Could you test it, please?

https://github.com/aferreira44/LinkedInBot

PS: It will run only on Python 3.x
